# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: 최승준
title: Backend Engineer
email: choie0423@naver.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  easdkr

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  더 좋은 서비스를 만들기 위해 비즈니스 도메인을 이해하려 노력하고, 나의 성장이 팀의 성장, 더 나아가 더 좋은 서비스의 성장으로 이끌 수 있도록 지속적으로 학습하고 노력하는 백엔드 개발자입니다.
  
  - <span style="font-size: 1.3rem"><span style="text-decoration: underline;">**함께 성장하기 위해 노력하는 사람들과 일하는 것을 좋아합니다.**</span> 나만의 성장보다는 팀 전체가 성장할 수 있도록 지속적으로 사내 스터디를 진행해오고 있습니다.</span>

  - <span style="font-size: 1.3rem"><span style="text-decoration: underline;">**더 나은 개발 문화를 만들기 위해 노력합니다.**</span> 
  모두가 동등한 입장에서 진행하는 코드리뷰 도입을 통해 다 같이 시나리오를 검증하고 서로의 코드를 이해하기 위해 노력하여 "우리 팀의 클린 코드"를 만드는 문화를 지향합니다.</span>

  - <span style="font-size: 1.3rem"><span style="text-decoration: underline;">**다양한 영역의 경험을 통해 더 나은 설계를 항상 고민합니다.**</span> Mobile app, Web Front-end 등 다양한 영역의 경험을 통해 항상 모두를 만족시킬 수 있는 설계를 하기 위해 노력합니다.</span>

content:
  - title: Career
    layout: list
    content:
      - layout: left
        title: 알파서클
        sub_title: 솔루션 및 서비스 개발
        link: https://alphacircle.co.kr
        caption: 2021.01 ~ 현재
        description: | # this will include new lines to allow paragraphs
          ## [Vroadway](https://play.google.com/store/apps/details?id=com.alphacircle.vroadway&hl=ko&gl=US&pli=1)
          <span style="font-size: 1.2rem; font-style: oblique;">360 VR 공연/전시 영상 서비스</span>
          
          Backend
          - **main skills: nest.js, typeorm, postgresql** 
          - 개발 생산성 증가를 위해 flask(python) 기반의 백엔드를 nest.js(typescript) 로 마이그레이션
          - 서비스 확장을 염두한 개선 아키텍처 설계
          - Database entity 구조 개선
          - jest와 supertest 기반의 unit, e2e 테스트 도입
          - github action 기반의 CI pipeline 구축
          - aws code pipeline과 ECS 기반의 CD pipeline 구축
          
          Frontend
          - **main skills: react**
          - 개발 생산성 증가를 위해 Angular(Typescript) 기반의 어드민을 React(Typescript) 로 마이그레이션
          - 재사용성을 위한 컴포넌트 구조 설계 및 개발
          - 컴포넌트 기반 개발을 위한 storybook 도입
          
          
          - 참고 링크 : [회고](https://github.com/easdkr/Vroadway-v2-api-server-retrospect)
          ---

          ## [신비아파트 VR뮤지컬](https://play.google.com/store/apps/details?id=com.shinbimusicalwadiz&hl=ko&gl=US)
          <span style="font-size: 1.2rem; font-style: oblique;">신비아파트 뮤지컬 VR 영상 서비스</span>
          - **main skills: flask, angular, react-native, aws**
          - 레거시 기반의 CMS 서버 및 어드민 페이지 배포
          - react native 기반의 모바일 앱 UI 기능 추가 및 개선
          
          ---
          
          ## [사내 VR 플레이어 솔루션 개발](https://www.youtube.com/watch?v=JfWsRtJclGk&t=2s)
          <span style="font-size: 1.2rem; font-style: oblique;">360 VR 초고화질 플레이어</span>
          - **main skills: android native(kotlin, java), exoplayer**
          - android exoplayer codec library 기반의 코덱 호환 검증 및 해상도 검증 라이브러리 개발
          - 구 버전의 exoplayer 기반의 레거시 솔루션을 신규 버전의 exoplayer 로 마이그레이션 및 개선 
          - 확장이 힘들었던 레거시 솔루션 코드를 다형성 기반의 코드로 변경하여 확장에 용이하도록 개선

         ---
         
         ## culture
         - 테스트 코드를 작성하는 문화 도입
         - github PR 기반의 코드 리뷰 문화 도입
         - 사내 스터디 그룹 문화 도입 
         
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 'Backend'
        quote: >
          현재 사용중이거나 사용했던 기술들입니다. (밑줄은 현재 주로 사용중인 기술을 의미합니다.) 
        description: | # this will include new lines to allow paragraphs
          - <span style="text-decoration: underline;">typescript(node.js)</span>, python3
          - <span style="text-decoration: underline;">nest.js</span>, flask
          - <span style="text-decoration: underline;">typeORM</span>, <span style="text-decoration: underline;">prisma</span>, sqlalchemy 
          - <span style="text-decoration: underline;">jest</span>, <span style="text-decoration: underline;">supertest</span>
          - celery 
      - layout: left
        title: 'Infra'
        description: | # this will include new lines to allow paragraphs
          - <span style="text-decoration: underline;">docker</span>, <span style="text-decoration: underline;">aws ecr</span>
          - <span style="text-decoration: underline;">aws ec2</span>, <span style="text-decoration: underline;">aws alb</span>, <span style="text-decoration: underline;">aws route53</span>, <span style="text-decoration: underline;">aws ecs</span>, <span style="text-decoration: underline;">aws rds</span>
          - <span style="text-decoration: underline;">aws s3</span>, <span style="text-decoration: underline;">aws cloudfront</span>
          - <span style="text-decoration: underline;">github action</span>, <span style="text-decoration: underline;">aws codedeploy</span>, <span style="text-decoration: underline;">aws code build</span>, <span style="text-decoration: underline;">aws codepipeline</span>
      - layout: left
        title: 'Frontend'
        description: | # this will include new lines to allow paragraphs
          - <span style="text-decoration: underline;">typescript</span>, <span style="text-decoration: underline;">jsx(tsx)</span>, rxjs
          - <span style="text-decoration: underline;">react</span>, angular
          - <span style="text-decoration: underline;">MUI</span>, angular/material
          - <span style="text-decoration: underline;">redux-toolkit</span>, <span style="text-decoration: underline;">recoil</span>
          - <span style="text-decoration: underline;">storybook/react</span>
          - vite, webpack
      - layout: left
        title: 'Mobile'
        description: |
          - <span style="text-decoration: underline;">typescript</span>, <span style="text-decoration: underline;">jsx(tsx)</span>, java, kotlin
          - <span style="text-decoration: underline;">react native</span>, android native
          - <span style="text-decoration: underline;">recoil</span>
  - title: Education
    layout: list
    content:
      - layout: left
        title: 금오공과대학교
        caption: 2012 - 2019
        description: | # this will include new lines to allow paragraphs
          컴퓨터공학과 (학사 졸업)
  - title: Paper
    layout: text 
    content: |  
        [Watch & Do: A Smart IoT Interaction System with Object Detection and Gaze Estimation](https://ieeexplore.ieee.org/document/8634883/)\
        <span style="font-size: 1.2rem; font-style: oblique; color:#636161;">(IEEE Transactions on Consumer Electronics, Vol 65, Issue 2, May, 2019 (Early Access))</span>
  - title: A Little More About Me
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: Study
        description: |
          - [clean code (로버트 C. 마틴)](https://github.com/alphacircle-service/clean-code-seminar) 사내 세미나 진행
          - clean architecture (로버트 C. 마틴), Unit Testing (블라디미르 코리코프) 독서 모임 진행 
          - [만들면서 배우는 헥사고날 아키텍처 설계와 구현(다비 비에이라) with Typescript](https://github.com/easdkr/hexagonal-architecture-with-typescript) 스터디 진행 
      - layout: left
        title: ETC
        description: |
          - 사내 솔루션용 git repository (Gitlab) 구축
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
